"""derived tables for the four dashboard screens

ward_quarter_index (the relative flooding index), watchlist_snapshots +
watchlist_entries (the standing top-20 with its measured context),
emerging_watch (the rank-based detector) and ward_allocation (spend against
ward size, which is the surviving effectiveness output).

All five are computed, never ingested; see ufms_schema.sql section 7 for the
reasoning behind each and app/derived/ for the computations. The wide decimals
on city_share, rel_index and the levels are deliberate — rounding the city
share to eight places moves the index by ~5e-7 and breaks the exact
reconciliation against the published panel.

Revision ID: 270818598e13
Revises: 5fabc9db9f7d
Create Date: 2026-09-09 01:41:53.283301
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '270818598e13'
down_revision: Union[str, None] = '5fabc9db9f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist_snapshots',
    sa.Column('snapshot_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('city_id', sa.SmallInteger().with_variant(mysql.SMALLINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('failure_type_id', sa.SmallInteger().with_variant(mysql.TINYINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False, comment='freeze date: entries rank on events up to and including this day'),
    sa.Column('k', sa.SmallInteger().with_variant(mysql.SMALLINT(unsigned=True), 'mysql'), server_default='20', nullable=False, comment='crew capacity, and the k in precision@k'),
    sa.Column('train_start', sa.Date(), nullable=False),
    sa.Column('test_start', sa.Date(), nullable=True, comment='NULL when the snapshot has not been scored'),
    sa.Column('test_end', sa.Date(), nullable=True),
    sa.Column('test_rain_days', sa.SmallInteger().with_variant(mysql.SMALLINT(unsigned=True), 'mysql'), nullable=True, comment='held-out days at or above rain_threshold_mm'),
    sa.Column('test_events', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=True, comment='citywide event-days on those rain days'),
    sa.Column('rain_threshold_mm', sa.Numeric(precision=5, scale=2), nullable=True, comment='city-mean daily rainfall that defines a rain day'),
    sa.Column('weather_model', sa.Enum('era5', 'ecmwf_ifs', 'era5_land', name='weathermodel'), nullable=True, comment='which reanalysis defined a rain day'),
    sa.Column('precision_at_k', sa.Numeric(precision=9, scale=8), nullable=True, comment='what the frozen list achieved'),
    sa.Column('oracle_at_k', sa.Numeric(precision=9, scale=8), nullable=True, comment='the ceiling: most nights carry fewer than k events citywide'),
    sa.Column('random_at_k', sa.Numeric(precision=9, scale=8), nullable=True, comment='expected precision of k wards drawn at random'),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.city_id'], name='fk_wls_city', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['failure_type_id'], ['failure_types.failure_type_id'], name='fk_wls_type', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id'),
    sa.UniqueConstraint('city_id', 'failure_type_id', 'as_of_date', 'k', name='uq_watchlist_snapshot')
    )
    op.create_index('idx_wls_as_of', 'watchlist_snapshots', ['city_id', 'as_of_date'], unique=False)
    op.create_table('emerging_watch',
    sa.Column('location_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False, comment='last day of the detection window'),
    sa.Column('window_start', sa.Date(), nullable=False),
    sa.Column('rank_position', sa.SmallInteger().with_variant(mysql.SMALLINT(unsigned=True), 'mysql'), nullable=False, comment='by first-half slope, which is the flag rule'),
    sa.Column('event_days', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False, comment='over the whole window; eligibility is >= 15'),
    sa.Column('half1_slope', sa.Numeric(precision=20, scale=16), nullable=False, comment='Theil-Sen on rel_index per quarter, first half'),
    sa.Column('half1_p', sa.Numeric(precision=19, scale=18), nullable=False, comment='Mann-Kendall on the same series'),
    sa.Column('half1_level', sa.Numeric(precision=20, scale=16), nullable=False, comment='mean rel_index over the first half'),
    sa.Column('half2_level', sa.Numeric(precision=20, scale=16), nullable=False),
    sa.Column('half2_slope', sa.Numeric(precision=20, scale=16), nullable=False),
    sa.Column('level_delta', sa.Numeric(precision=21, scale=16), nullable=False, comment='half2_level minus half1_level'),
    sa.Column('full_slope', sa.Numeric(precision=20, scale=16), nullable=False, comment='Theil-Sen over the whole window'),
    sa.Column('full_p', sa.Numeric(precision=19, scale=18), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), server_default='0', nullable=False, comment='inside the top-N cut this run used'),
    sa.Column('on_register', sa.Boolean(), server_default='0', nullable=False, comment='already on the BBMP flood register'),
    sa.Column('label', sa.String(length=40), server_default='chronically_above_norm', nullable=False, comment='what the detector was measured to find, not what it was hoped to find'),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], name='fk_ew_location', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'as_of_date')
    )
    op.create_index('idx_ew_rank', 'emerging_watch', ['as_of_date', 'rank_position'], unique=False)
    op.create_table('ward_allocation',
    sa.Column('location_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False),
    sa.Column('window_start', sa.Date(), nullable=False, comment='first work completion date counted'),
    sa.Column('window_end', sa.Date(), nullable=False),
    sa.Column('drainage_works', sa.SmallInteger().with_variant(mysql.SMALLINT(unsigned=True), 'mysql'), nullable=False, comment='work orders classified as drainage completing in the window'),
    sa.Column('drainage_spend', sa.Numeric(precision=16, scale=2), nullable=False, comment='INR, nett of deductions'),
    sa.Column('ward_area_sqkm', sa.Numeric(precision=8, scale=2), nullable=True, comment='what spend actually tracks'),
    sa.Column('event_days_pre', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False),
    sa.Column('event_days_post', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False),
    sa.Column('event_days_total', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False, comment='over the whole index window: the absolute-volume axis of the targeting check'),
    sa.Column('pre_index', sa.Numeric(precision=20, scale=16), nullable=False, comment='mean rel_index over the pre quarters'),
    sa.Column('post_index', sa.Numeric(precision=20, scale=16), nullable=False),
    sa.Column('delta_index', sa.Numeric(precision=21, scale=16), nullable=False, comment='post minus pre. Descriptive. NOT an effect of spend.'),
    sa.Column('is_treated', sa.Boolean(), nullable=False, comment='any drainage work in the window. 103 of 110; not a usable control split.'),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], name='fk_wa_location', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'window_start', 'window_end')
    )
    op.create_index('idx_wa_spend', 'ward_allocation', ['drainage_spend'], unique=False)
    op.create_table('ward_quarter_index',
    sa.Column('location_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False),
    sa.Column('period_type', sa.Enum('month', 'quarter', 'year', name='periodtype'), server_default='quarter', nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False, comment='first day of the period'),
    sa.Column('event_days', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False, comment='distinct ward-days carrying a strict waterlogging event'),
    sa.Column('total_complaints', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False, comment='the denominator, from ward_period_totals: all categories'),
    sa.Column('city_share', sa.Numeric(precision=20, scale=18), nullable=False, comment='citywide event-days over citywide complaints, this period'),
    sa.Column('smoothing', sa.Numeric(precision=4, scale=2), server_default='0.50', nullable=False, comment='added to numerator and denominator; 0.5 in the published panel'),
    sa.Column('rel_index', sa.Numeric(precision=20, scale=16), nullable=False, comment='1.00 is the city norm for that quarter'),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], name='fk_wqi_location', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'period_type', 'period_start')
    )
    op.create_index('idx_wqi_period', 'ward_quarter_index', ['period_type', 'period_start'], unique=False)
    op.create_table('watchlist_entries',
    sa.Column('snapshot_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False),
    sa.Column('rank_position', sa.SmallInteger().with_variant(mysql.SMALLINT(unsigned=True), 'mysql'), nullable=False, comment='1 is worst; ties broken by area name so the order is stable'),
    sa.Column('location_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False),
    sa.Column('prior_events', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False, comment='event-days up to as_of_date. The entire ranking key.'),
    sa.Column('test_events', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=True, comment='event-days on the held-out rain days, for the per-ward column'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], name='fk_wle_location', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['watchlist_snapshots.snapshot_id'], name='fk_wle_snapshot', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id', 'rank_position'),
    sa.UniqueConstraint('snapshot_id', 'location_id', name='uq_watchlist_entry')
    )
    op.create_index('idx_wle_location', 'watchlist_entries', ['location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Tables only, in reverse dependency order. The autogenerated version
    # dropped each index first and failed: `idx_wle_location` is the index
    # MySQL uses to enforce `fk_wle_location`, so dropping it while the table
    # still exists raises errno 1553. DROP TABLE takes the indexes with it.
    op.drop_table('watchlist_entries')
    op.drop_table('watchlist_snapshots')
    op.drop_table('ward_allocation')
    op.drop_table('emerging_watch')
    op.drop_table('ward_quarter_index')
