"""ward_period_totals: the index denominator, in the database

Revision ID: 5fabc9db9f7d
Revises: bcaacf1141de
Create Date: 2026-09-08 21:56:29.214278
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '5fabc9db9f7d'
down_revision: Union[str, None] = 'bcaacf1141de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ward_period_totals',
    sa.Column('location_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False),
    sa.Column('period_type', sa.Enum('month', 'quarter', 'year', name='periodtype'), server_default='quarter', nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False, comment='first day of the period'),
    sa.Column('total_complaints', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False, comment='all categories, not just hazards'),
    sa.Column('run_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], name='fk_wpt_location', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.run_id'], name='fk_wpt_run', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('location_id', 'period_type', 'period_start')
    )
    op.create_index('idx_wpt_period', 'ward_period_totals', ['period_type', 'period_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_wpt_period', table_name='ward_period_totals')
    op.drop_table('ward_period_totals')
    # ### end Alembic commands ###
