"""baseline: 26 tables and 3 views, matching ufms_schema.sql

Revision ID: d592327e5d7c
Revises: 
Create Date: 2026-09-08 21:52:10.891216
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'd592327e5d7c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



# --------------------------------------------------------------------------
# The three convenience views. Alembic autogenerates tables but never
# views, so they are hand-carried here verbatim from ufms_schema.sql
# section 8. tests/test_migrations.py is what keeps the two in step: it
# builds one database each way and diffs information_schema.
# --------------------------------------------------------------------------
VIEWS: dict[str, str] = {
    "v_prediction_outcomes": """
CREATE OR REPLACE VIEW v_prediction_outcomes AS
SELECT
    m.name              AS model_name,
    m.feature_set,
    p.predicted_for_date,
    p.risk_level,
    COUNT(*)                                                    AS n_predictions,
    SUM(p.actual_outcome = 'failure')                           AS n_failures,
    ROUND(SUM(p.actual_outcome = 'failure') / NULLIF(COUNT(*),0), 4) AS hit_rate
FROM risk_predictions p
JOIN models m ON m.model_id = p.model_id
WHERE p.actual_outcome IN ('failure','no_failure')
GROUP BY m.name, m.feature_set, p.predicted_for_date, p.risk_level
""",
    "v_precision_at_k": """
CREATE OR REPLACE VIEW v_precision_at_k AS
SELECT
    r.ranking_date,
    r.city_id,
    r.model_id,
    COUNT(*)                                        AS k,
    SUM(p.actual_outcome = 'failure')               AS hits,
    ROUND(SUM(p.actual_outcome = 'failure') / NULLIF(COUNT(*),0), 4) AS precision_at_k
FROM daily_rankings r
LEFT JOIN risk_predictions p
       ON p.location_id        = r.location_id
      AND p.failure_type_id    = r.failure_type_id
      AND p.predicted_for_date = r.ranking_date
      AND p.model_id           = r.model_id
WHERE r.in_top_k = TRUE
GROUP BY r.ranking_date, r.city_id, r.model_id
""",
    "v_unverified_hotspots": """
CREATE OR REPLACE VIEW v_unverified_hotspots AS
SELECT l.location_id, c.name AS city, l.area_name, l.ward_no, l.first_listed_year
FROM locations l
JOIN cities c ON c.city_id = l.city_id
LEFT JOIN failures f ON f.location_id = l.location_id
WHERE l.is_known_hotspot = TRUE
GROUP BY l.location_id, c.name, l.area_name, l.ward_no, l.first_listed_year
HAVING COUNT(f.failure_id) = 0
""",
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('city_id', sa.SmallInteger().with_variant(mysql.SMALLINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.Column('country', sa.CHAR(length=2), server_default='IN', nullable=False),
    sa.Column('centroid_lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('centroid_lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('timezone', sa.String(length=40), server_default='Asia/Kolkata', nullable=False),
    sa.Column('role', sa.Enum('primary', 'demo', name='cityrole'), nullable=False),
    sa.Column('monsoon_start_month', sa.SmallInteger().with_variant(mysql.TINYINT(unsigned=True), 'mysql'), nullable=False, comment='local season start, for season_position feature'),
    sa.Column('monsoon_end_month', sa.SmallInteger().with_variant(mysql.TINYINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('city_id'),
    sa.UniqueConstraint('name', 'state', name='uq_cities_name')
    )
    op.create_table('data_sources',
    sa.Column('source_id', sa.SmallInteger().with_variant(mysql.SMALLINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('licence', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('source_id'),
    sa.UniqueConstraint('name', name='uq_source_name')
    )
    op.create_table('failure_types',
    sa.Column('failure_type_id', sa.SmallInteger().with_variant(mysql.TINYINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('scope', sa.Enum('modelled', 'operational', 'schema_only', name='failurescope'), server_default='schema_only', nullable=False),
    sa.PrimaryKeyConstraint('failure_type_id'),
    sa.UniqueConstraint('code', name='uq_failure_code')
    )
    op.create_table('models',
    sa.Column('model_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('algorithm', sa.Enum('threshold_rule', 'logistic_regression', 'decision_tree', 'random_forest', 'gradient_boosting', 'other', name='algorithm'), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('city_id', sa.SmallInteger().with_variant(mysql.SMALLINT(unsigned=True), 'mysql'), nullable=True),
    sa.Column('failure_type_id', sa.SmallInteger().with_variant(mysql.TINYINT(unsigned=True), 'mysql'), nullable=True),
    sa.Column('feature_set', sa.Enum('M0_threshold', 'M1_weather', 'M2_weather_geo', 'M3_full_memory', name='featureset'), nullable=False),
    sa.Column('train_start', sa.Date(), nullable=True),
    sa.Column('train_end', sa.Date(), nullable=True),
    sa.Column('test_start', sa.Date(), nullable=True),
    sa.Column('test_end', sa.Date(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True, comment='pr_auc, precision_at_20, brier, ece, base_rate'),
    sa.Column('artifact_path', sa.String(length=400), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('trained_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('model_id'),
    sa.UniqueConstraint('name', 'version', name='uq_model_name_version')
    )
    op.create_index('idx_model_active', 'models', ['is_active', 'city_id'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('run_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.SmallInteger().with_variant(mysql.SMALLINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('rows_ingested', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), server_default=sa.text('0'), nullable=False),
    sa.Column('rows_rejected', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.Enum('running', 'success', 'failed', 'partial', name='ingestionstatus'), server_default='running', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], name='fk_run_source', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index('idx_run_source_time', 'ingestion_runs', ['source_id', 'started_at'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=190), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='bcrypt/argon2 — never store plaintext'),
    sa.Column('role', sa.Enum('admin', 'officer', name='userrole'), server_default='officer', nullable=False),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('city_id', sa.SmallInteger().with_variant(mysql.SMALLINT(unsigned=True), 'mysql'), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.city_id'], name='fk_user_city', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index('idx_users_city', 'users', ['city_id'], unique=False)
    op.create_table('weather_cells',
    sa.Column('cell_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('city_id', sa.SmallInteger().with_variant(mysql.SMALLINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('elevation_m', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.city_id'], name='fk_cell_city', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cell_id'),
    sa.UniqueConstraint('latitude', 'longitude', name='uq_cell_coords')
    )
    op.create_index('idx_cell_city', 'weather_cells', ['city_id'], unique=False)
    op.create_table('locations',
    sa.Column('location_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('city_id', sa.SmallInteger().with_variant(mysql.SMALLINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('cell_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=True, comment='nearest ERA5 weather cell'),
    sa.Column('area_name', sa.String(length=200), nullable=False),
    sa.Column('ward_no', sa.String(length=20), nullable=True),
    sa.Column('ward_name', sa.String(length=150), nullable=True),
    sa.Column('zone', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('geom_level', sa.Enum('ward', 'point', 'grid', name='geomlevel'), server_default='ward', nullable=False),
    sa.Column('is_known_hotspot', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('hotspot_source', sa.String(length=120), nullable=True),
    sa.Column('first_listed_year', sa.SmallInteger().with_variant(mysql.SMALLINT(unsigned=True), 'mysql'), nullable=True, comment='year it first appeared on the official list'),
    sa.Column('last_listed_year', sa.SmallInteger().with_variant(mysql.SMALLINT(unsigned=True), 'mysql'), nullable=True, comment='NULL if still listed, set when it drops off'),
    sa.Column('elevation_m', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('imperviousness', sa.Numeric(precision=5, scale=2), nullable=True, comment='percent, from land cover'),
    sa.Column('drain_distance_m', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('population', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['cell_id'], ['weather_cells.cell_id'], name='fk_location_cell', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.city_id'], name='fk_location_city', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id'),
    sa.UniqueConstraint('city_id', 'area_name', 'geom_level', name='uq_location_city_area')
    )
    op.create_index('idx_location_cell', 'locations', ['cell_id'], unique=False)
    op.create_index('idx_location_city', 'locations', ['city_id'], unique=False)
    op.create_index('idx_location_coords', 'locations', ['latitude', 'longitude'], unique=False)
    op.create_index('idx_location_hotspot', 'locations', ['city_id', 'is_known_hotspot'], unique=False)
    op.create_index('idx_location_ward', 'locations', ['city_id', 'ward_no'], unique=False)
    op.create_table('weather_daily',
    sa.Column('cell_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False),
    sa.Column('obs_date', sa.Date(), nullable=False),
    sa.Column('rain_24h_mm', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('rain_1h_max_mm', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('rain_3h_max_mm', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('antecedent_7d_mm', sa.Numeric(precision=8, scale=2), nullable=True, comment='prior-week total, a soil saturation proxy'),
    sa.Column('rain_percentile', sa.Numeric(precision=6, scale=5), nullable=True, comment='rank of rain_24h in this cell own history'),
    sa.Column('return_period_yrs', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('season_position', sa.SmallInteger(), nullable=True, comment='days into the LOCAL monsoon, not calendar month'),
    sa.Column('temp_mean_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('humidity_mean_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['cell_id'], ['weather_cells.cell_id'], name='fk_wd_cell', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cell_id', 'obs_date')
    )
    op.create_index('idx_wd_date', 'weather_daily', ['obs_date'], unique=False)
    op.create_table('weather_observations',
    sa.Column('weather_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('cell_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('rainfall_mm', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('temperature_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('humidity_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('wind_speed_ms', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('source_id', sa.SmallInteger().with_variant(mysql.SMALLINT(unsigned=True), 'mysql'), nullable=True),
    sa.ForeignKeyConstraint(['cell_id'], ['weather_cells.cell_id'], name='fk_weather_cell', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], name='fk_weather_source', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('weather_id'),
    sa.UniqueConstraint('cell_id', 'recorded_at', name='uq_weather_cell_time')
    )
    op.create_index('idx_weather_time', 'weather_observations', ['recorded_at'], unique=False)
    op.create_table('complaints',
    sa.Column('complaint_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False),
    sa.Column('failure_type_id', sa.SmallInteger().with_variant(mysql.TINYINT(unsigned=True), 'mysql'), nullable=True),
    sa.Column('external_id', sa.String(length=80), nullable=True, comment='id in the source system, for dedup'),
    sa.Column('reported_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(length=150), nullable=True, comment='raw category string from source'),
    sa.Column('sub_category', sa.String(length=150), nullable=True),
    sa.Column('status', sa.Enum('registered', 'in_progress', 'closed', 'reopened', 'long_term', 'not_relevant', 'unknown', name='complaintstatus'), server_default='unknown', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_id', sa.SmallInteger().with_variant(mysql.SMALLINT(unsigned=True), 'mysql'), nullable=True),
    sa.Column('run_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=True),
    sa.ForeignKeyConstraint(['failure_type_id'], ['failure_types.failure_type_id'], name='fk_complaint_type', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], name='fk_complaint_location', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.run_id'], name='fk_complaint_run', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], name='fk_complaint_source', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('complaint_id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_complaint_external')
    )
    op.create_index('idx_complaint_loc_time', 'complaints', ['location_id', 'reported_at'], unique=False)
    op.create_index('idx_complaint_type_time', 'complaints', ['failure_type_id', 'reported_at'], unique=False)
    op.create_table('daily_rankings',
    sa.Column('ranking_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('city_id', sa.SmallInteger().with_variant(mysql.SMALLINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('failure_type_id', sa.SmallInteger().with_variant(mysql.TINYINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('ranking_date', sa.Date(), nullable=False),
    sa.Column('location_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False),
    sa.Column('rank_position', sa.SmallInteger().with_variant(mysql.SMALLINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('score', sa.Numeric(precision=7, scale=6), nullable=False),
    sa.Column('model_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False),
    sa.Column('in_top_k', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='was it dispatched to?'),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.city_id'], name='fk_rank_city', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['failure_type_id'], ['failure_types.failure_type_id'], name='fk_rank_type', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], name='fk_rank_location', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], name='fk_rank_model', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ranking_id'),
    sa.UniqueConstraint('city_id', 'failure_type_id', 'ranking_date', 'location_id', 'model_id', name='uq_ranking')
    )
    op.create_index('idx_ranking_date_pos', 'daily_rankings', ['ranking_date', 'rank_position'], unique=False)
    op.create_table('detected_patterns',
    sa.Column('pattern_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=True, comment='NULL = city-wide rule'),
    sa.Column('failure_type_id', sa.SmallInteger().with_variant(mysql.TINYINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('feature', sa.String(length=80), nullable=False),
    sa.Column('operator', sa.Enum('>', '>=', '<', '<=', '=', 'between', name='patternoperator'), nullable=False),
    sa.Column('threshold_value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('threshold_upper', sa.Numeric(precision=12, scale=4), nullable=True, comment='used when operator = between'),
    sa.Column('season', sa.String(length=40), nullable=True),
    sa.Column('support_count', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('lift', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['failure_type_id'], ['failure_types.failure_type_id'], name='fk_pattern_type', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], name='fk_pattern_location', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pattern_id')
    )
    op.create_index('idx_pattern_conf', 'detected_patterns', ['confidence'], unique=False)
    op.create_index('idx_pattern_loc_type', 'detected_patterns', ['location_id', 'failure_type_id'], unique=False)
    op.create_table('emerging_locations',
    sa.Column('emerging_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False),
    sa.Column('failure_type_id', sa.SmallInteger().with_variant(mysql.TINYINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('method', sa.Enum('mann_kendall', 'cusum', 'pettitt', 'other', name='emergingmethod'), nullable=False),
    sa.Column('trend_statistic', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('p_value', sa.Numeric(precision=8, scale=7), nullable=True),
    sa.Column('changepoint_date', sa.Date(), nullable=True),
    sa.Column('months_of_evidence', sa.SmallInteger().with_variant(mysql.SMALLINT(unsigned=True), 'mysql'), nullable=True),
    sa.Column('status', sa.Enum('candidate', 'confirmed', 'dismissed', name='emergingstatus'), server_default='candidate', nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['failure_type_id'], ['failure_types.failure_type_id'], name='fk_emerging_type', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], name='fk_emerging_location', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('emerging_id'),
    sa.UniqueConstraint('location_id', 'failure_type_id', 'detected_at', name='uq_emerging')
    )
    op.create_index('idx_emerging_status', 'emerging_locations', ['status', 'detected_at'], unique=False)
    op.create_table('failure_memory',
    sa.Column('memory_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False),
    sa.Column('failure_type_id', sa.SmallInteger().with_variant(mysql.TINYINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('recurrence_count', sa.SmallInteger().with_variant(mysql.SMALLINT(unsigned=True), 'mysql'), nullable=True),
    sa.Column('recurrence_rate', sa.Numeric(precision=7, scale=4), nullable=True, comment='events per season'),
    sa.Column('recurrence_percentile', sa.Numeric(precision=6, scale=5), nullable=True, comment='rank within city — this is what transfers'),
    sa.Column('days_since_last', sa.Integer(), nullable=True),
    sa.Column('severity_ema', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('rain_sensitivity_mm', sa.Numeric(precision=7, scale=2), nullable=True, comment='rainfall at which THIS location has historically failed'),
    sa.Column('neighbour_memory', sa.Numeric(precision=7, scale=4), nullable=True, comment='same stats within 1 km'),
    sa.Column('baseline_complaint_rate', sa.Numeric(precision=9, scale=4), nullable=True, comment='reporting-bias control'),
    sa.ForeignKeyConstraint(['failure_type_id'], ['failure_types.failure_type_id'], name='fk_memory_type', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], name='fk_memory_location', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('memory_id'),
    sa.UniqueConstraint('location_id', 'failure_type_id', 'as_of_date', name='uq_memory')
    )
    op.create_index('idx_memory_asof', 'failure_memory', ['as_of_date'], unique=False)
    op.create_table('infrastructure_assets',
    sa.Column('asset_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False),
    sa.Column('asset_type', sa.Enum('drain', 'culvert', 'pump', 'underpass', 'sewer_line', 'catch_basin', 'road', 'other', name='assettype'), nullable=False),
    sa.Column('installation_date', sa.Date(), nullable=True),
    sa.Column('capacity_note', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('operational', 'degraded', 'failed', 'unknown', name='assetstatus'), server_default='unknown', nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], name='fk_asset_location', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_index('idx_asset_location', 'infrastructure_assets', ['location_id'], unique=False)
    op.create_table('interventions',
    sa.Column('intervention_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False),
    sa.Column('failure_type_id', sa.SmallInteger().with_variant(mysql.TINYINT(unsigned=True), 'mysql'), nullable=True),
    sa.Column('intervention_type', sa.Enum('desilting', 'drain_cleaning', 'drain_widening', 'pump_installation', 'road_raising', 'sewer_repair', 'other', name='interventiontype'), nullable=False),
    sa.Column('agency', sa.String(length=120), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('cost_inr', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('external_ref', sa.String(length=120), nullable=True, comment='work order number'),
    sa.Column('source_id', sa.SmallInteger().with_variant(mysql.SMALLINT(unsigned=True), 'mysql'), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], name='fk_intervention_location', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], name='fk_intervention_source', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('intervention_id')
    )
    op.create_index('idx_intervention_loc_date', 'interventions', ['location_id', 'start_date'], unique=False)
    op.create_table('risk_predictions',
    sa.Column('prediction_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False),
    sa.Column('failure_type_id', sa.SmallInteger().with_variant(mysql.TINYINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('model_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False),
    sa.Column('predicted_for_date', sa.Date(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=7, scale=6), nullable=False, comment='calibrated probability 0..1'),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', name='risklevel'), nullable=False),
    sa.Column('feature_snapshot', sa.JSON(), nullable=True, comment='exact inputs, for reproducibility'),
    sa.Column('actual_outcome', sa.Enum('pending', 'failure', 'no_failure', 'unknown', name='predictionoutcome'), server_default='pending', nullable=False),
    sa.Column('outcome_recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['failure_type_id'], ['failure_types.failure_type_id'], name='fk_pred_type', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], name='fk_pred_location', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], name='fk_pred_model', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('prediction_id'),
    sa.UniqueConstraint('location_id', 'failure_type_id', 'predicted_for_date', 'model_id', name='uq_prediction')
    )
    op.create_index('idx_pred_date', 'risk_predictions', ['predicted_for_date', 'risk_score'], unique=False)
    op.create_index('idx_pred_outcome', 'risk_predictions', ['actual_outcome', 'predicted_for_date'], unique=False)
    op.create_table('sanitation_data',
    sa.Column('sanitation_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('garbage_volume_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('collection_status', sa.Enum('collected', 'missed', 'partial', 'unknown', name='collectionstatus'), server_default='unknown', nullable=False),
    sa.Column('source_id', sa.SmallInteger().with_variant(mysql.SMALLINT(unsigned=True), 'mysql'), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], name='fk_sanitation_location', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sanitation_id'),
    sa.UniqueConstraint('location_id', 'recorded_at', name='uq_sanitation_loc_time')
    )
    op.create_table('traffic_data',
    sa.Column('traffic_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('vehicle_count', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=True),
    sa.Column('congestion_level', sa.Enum('free', 'light', 'moderate', 'heavy', 'gridlock', name='congestionlevel'), nullable=True),
    sa.Column('average_speed_kmph', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('source_id', sa.SmallInteger().with_variant(mysql.SMALLINT(unsigned=True), 'mysql'), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], name='fk_traffic_location', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('traffic_id'),
    sa.UniqueConstraint('location_id', 'recorded_at', name='uq_traffic_loc_time')
    )
    op.create_table('alerts',
    sa.Column('alert_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('prediction_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=True),
    sa.Column('emerging_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=True),
    sa.Column('city_id', sa.SmallInteger().with_variant(mysql.SMALLINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('target_role', sa.Enum('admin', 'officer', 'all', name='targetrole'), server_default='officer', nullable=False),
    sa.Column('alert_type', sa.Enum('nightly_triage', 'emerging_hotspot', 'threshold_breach', name='alerttype'), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='alertseverity'), server_default='warning', nullable=False),
    sa.Column('alert_message', sa.Text(), nullable=False),
    sa.Column('alert_status', sa.Enum('queued', 'sent', 'failed', 'acknowledged', name='alertstatus'), server_default='queued', nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.city_id'], name='fk_alert_city', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['emerging_id'], ['emerging_locations.emerging_id'], name='fk_alert_emerging', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prediction_id'], ['risk_predictions.prediction_id'], name='fk_alert_prediction', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index('idx_alert_city', 'alerts', ['city_id', 'created_at'], unique=False)
    op.create_index('idx_alert_status', 'alerts', ['alert_status', 'created_at'], unique=False)
    op.create_table('failures',
    sa.Column('failure_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('failure_type_id', sa.SmallInteger().with_variant(mysql.TINYINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('location_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False),
    sa.Column('asset_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.Column('severity_level', sa.Enum('low', 'medium', 'high', 'critical', name='severity'), server_default='medium', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('derived_from', sa.Enum('manual', 'complaint_cluster', 'news', 'agency_report', name='derivedfrom'), server_default='manual', nullable=False),
    sa.Column('complaint_count', sa.SmallInteger().with_variant(mysql.SMALLINT(unsigned=True), 'mysql'), nullable=True, comment='size of the cluster, if derived'),
    sa.Column('source_id', sa.SmallInteger().with_variant(mysql.SMALLINT(unsigned=True), 'mysql'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['infrastructure_assets.asset_id'], name='fk_failure_asset', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['failure_type_id'], ['failure_types.failure_type_id'], name='fk_failure_type', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], name='fk_failure_location', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], name='fk_failure_source', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('failure_id')
    )
    op.create_index('idx_failure_loc_time', 'failures', ['location_id', 'occurred_at'], unique=False)
    op.create_index('idx_failure_occurred', 'failures', ['occurred_at'], unique=False)
    op.create_index('idx_failure_type_time', 'failures', ['failure_type_id', 'occurred_at'], unique=False)
    op.create_table('intervention_effects',
    sa.Column('effect_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('intervention_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.Column('window_months', sa.SmallInteger().with_variant(mysql.SMALLINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('treated_pre_rate', sa.Numeric(precision=9, scale=5), nullable=True),
    sa.Column('treated_post_rate', sa.Numeric(precision=9, scale=5), nullable=True),
    sa.Column('control_pre_rate', sa.Numeric(precision=9, scale=5), nullable=True),
    sa.Column('control_post_rate', sa.Numeric(precision=9, scale=5), nullable=True),
    sa.Column('control_n', sa.SmallInteger().with_variant(mysql.SMALLINT(unsigned=True), 'mysql'), nullable=True),
    sa.Column('did_estimate', sa.Numeric(precision=9, scale=5), nullable=True, comment='negative = failures reduced'),
    sa.Column('p_value', sa.Numeric(precision=8, scale=7), nullable=True),
    sa.Column('verdict', sa.Enum('effective', 'no_effect', 'worse', 'inconclusive', name='effectverdict'), server_default='inconclusive', nullable=False),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.intervention_id'], name='fk_effect_intervention', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('effect_id'),
    sa.UniqueConstraint('intervention_id', 'evaluated_at', 'window_months', name='uq_effect')
    )
    op.create_table('preventive_actions',
    sa.Column('action_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('prediction_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=True),
    sa.Column('location_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False),
    sa.Column('user_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('action_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('planned', 'in_progress', 'completed', 'cancelled', name='actionstatus'), server_default='planned', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], name='fk_action_location', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prediction_id'], ['risk_predictions.prediction_id'], name='fk_action_prediction', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='fk_action_user', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_index('idx_action_loc_date', 'preventive_actions', ['location_id', 'action_date'], unique=False)
    op.create_table('alert_recipients',
    sa.Column('alert_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('user_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.alert_id'], name='fk_ar_alert', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='fk_ar_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alert_id', 'user_id')
    )
    op.create_index('idx_ar_user', 'alert_recipients', ['user_id'], unique=False)
    op.create_table('complaint_failure_link',
    sa.Column('complaint_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('failure_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.complaint_id'], name='fk_cfl_complaint', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['failure_id'], ['failures.failure_id'], name='fk_cfl_failure', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('complaint_id', 'failure_id')
    )
    op.create_index('idx_cfl_failure', 'complaint_failure_link', ['failure_id'], unique=False)
    # ### end Alembic commands ###

    for ddl in VIEWS.values():
        op.execute(ddl)


def downgrade() -> None:
    for name in reversed(list(VIEWS)):
        op.execute(f"DROP VIEW IF EXISTS {name}")

    # ### commands auto generated by Alembic - please adjust! ###
    # Every index here sits on a table this same function drops, so the
    # autogenerated op.drop_index() calls were redundant - and two of them
    # were also impossible: MySQL refuses to drop an index a foreign key
    # still needs (idx_cfl_failure backs fk_cfl_failure). Dropping the
    # table takes its indexes with it.
    op.drop_table('complaint_failure_link')
    op.drop_table('alert_recipients')
    op.drop_table('preventive_actions')
    op.drop_table('intervention_effects')
    op.drop_table('failures')
    op.drop_table('alerts')
    op.drop_table('traffic_data')
    op.drop_table('sanitation_data')
    op.drop_table('risk_predictions')
    op.drop_table('interventions')
    op.drop_table('infrastructure_assets')
    op.drop_table('failure_memory')
    op.drop_table('emerging_locations')
    op.drop_table('detected_patterns')
    op.drop_table('daily_rankings')
    op.drop_table('complaints')
    op.drop_table('weather_observations')
    op.drop_table('weather_daily')
    op.drop_table('locations')
    op.drop_table('weather_cells')
    op.drop_table('users')
    op.drop_table('ingestion_runs')
    op.drop_table('models')
    op.drop_table('failure_types')
    op.drop_table('data_sources')
    op.drop_table('cities')
    # ### end Alembic commands ###
